# Generated by Django 4.2.4 on 2024-01-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_1', models.CharField(max_length=500)),
                ('opt_2', models.CharField(max_length=500)),
                ('opt_3', models.CharField(max_length=500)),
                ('opt_4', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=500)),
                ('time_limit', models.IntegerField()),
                ('right_opt', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAMS_Quiz.quizset')),
            ],
        ),
    ]
