# Generated by Django 4.2.4 on 2024-01-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAMS_Quiz', '0003_usersubmittedanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedanswer',
            name='right_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
