# Generated by Django 4.2.4 on 2023-09-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_language_course_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='Language',
            new_name='language',
        ),
    ]
