# Generated by Django 4.2.4 on 2023-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_video_thumbnail_remove_video_youtube_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(null=True, upload_to='Media/author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_video',
            field=models.FileField(null=True, upload_to='Media/featured_video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
