# Generated by Django 4.2.4 on 2024-01-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_cybersourcetransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CyberSourceTransaction',
        ),
    ]
