# Generated by Django 4.2.4 on 2024-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAMS_Res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cams_files',
            name='files_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
