# Generated by Django 4.2.4 on 2024-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAMS_Res', '0003_remove_cams_files_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMSFILES_VIEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('word_files', models.FileField(upload_to='Media/Resources')),
                ('files_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cams_files',
            name='filename',
            field=models.CharField(max_length=500),
        ),
    ]
