# Generated by Django 4.2.4 on 2024-01-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAMS_Res', '0004_camsfiles_view_alter_cams_files_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CAMSFILES_VIEW',
        ),
    ]
